# Generated by Django 5.1.7 on 2025-03-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_alter_comment_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.PositiveIntegerField(choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=0),
        ),
    ]
